animecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	 path('', views.home, name='home'),
      path('about/', views.about, name='about'),
      path('anime/', views.anime_index, name='index'),
      path('anime/<int:anime_id>', views.anime_detail, name='detail'),
      path('anime/create/', views.AnimeCreate.as_view(), name='anime_create'),
      path('anime/<int:pk>/update/', views.AnimeUpdate.as_view(), name='anime_update'),
      path('anime/<int:pk>/delete/', views.AnimeDelete.as_view(), name='anime_delete'), 
      path('anime/<int:anime_id>/add_episode/', views.add_episode, name='add_episode'),  
      path('characters/', views.CharacterList.as_view(), name='characters_index'),
      path('characters/<int:pk>/', views.CharacterDetail.as_view(), name='characters_detail'),
      path('characters/create/', views.CharacterCreate.as_view(), name='characters_create'),
      path('characters/<int:pk>/update/', views.CharacterUpdate.as_view(), name='characters_update'),
      path('characters/<int:pk>/delete/', views.CharacterDelete.as_view(), name='characters_delete'),
      path('characters/<int:anime_id>/assoc_character/<int:character_id>/', views.assoc_character, name='assoc_character'),
      path('characters/<int:anime_id>/remove_character/<int:character_id>/', views.remove_character, name='remove_character'),
 ]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

RATINGS = (
    ('B', 'Bad'),
    ('G', 'Good'),
    ('A', 'Awesome')
)

# Create your models here.

class Character(models.Model):
  name = models.CharField(max_length=50)
  description = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('characters_detail', kwargs={'pk': self.id})

class Anime(models.Model):
    title = models.CharField(max_length=100)
    creator = models.CharField(max_length=100)
    genre = models.TextField(max_length=250)
    release_year=models.IntegerField()
    characters = models.ManyToManyField(Character)

    def __str__(self):
        return f'{self.title} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'anime_id': self.id})
    
class Episode(models.Model):
  date = models.DateField('episode date')
  rating = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=RATINGS,

    default=RATINGS[0][0]
  )
  
  anime = models.ForeignKey(Anime, on_delete=models.CASCADE)
  
  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_rating_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
# forms.py

from django.forms import ModelForm
from .models import Episode

class EpisodeForm(ModelForm):
  class Meta:
    model = Episode
    fields = ['date', 'rating']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Anime, Character
from .forms import EpisodeForm


anime = [
  {'title': 'Naruto', 'creator': 'Masashi Kishimoto', 'genre': 'shounen', 'release_year': 2005},
  {'title': 'Jujutsu Kaisen', 'creator': 'Gege Akutami', 'genre': 'shounen', 'release_year': 2020},
]



# Create your views here.


def home(request):
  # Include an .html file extension - unlike when rendering EJS templates
  return render(request, 'home.html')

def about(request):
  # Include an .html file extension - unlike when rendering EJS templates
  return render(request, 'about.html')

def anime_index(request):
  # Include an .html file extension - unlike when rendering EJS templates
  anime = Anime.objects.all()
  return render(request, 'anime/index.html', { 'anime': anime})

def anime_detail(request, anime_id):
    anime = Anime.objects.get(id=anime_id)
    id_list = anime.characters.all().values_list('id')
    characters_anime_doesnt_have = Character.objects.exclude(id__in=id_list)
    episode_form = EpisodeForm()
    return render(request, 'anime/detail.html', {
      'anime': anime, 'episode_form': episode_form,
      'characters': characters_anime_doesnt_have
      })

def assoc_character(request, anime_id, character_id):
    # Note that you can pass a toy's id instead of the whole toy object
    Anime.objects.get(id=anime_id).characters.add(character_id)
    return redirect('detail', anime_id=anime_id)

def remove_character(request, anime_id, character_id):
    # Note that you can pass a toy's id instead of the whole toy object
    Anime.objects.get(id=anime_id).characters.remove(character_id)
    return redirect('detail', anime_id=anime_id)

def add_episode(request, anime_id):
 # create a ModelForm instance using the data in request.POST
  form = EpisodeForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_episode = form.save(commit=False)
    new_episode.anime_id = anime_id
    new_episode.save()
  return redirect('detail', anime_id=anime_id)

class AnimeCreate(CreateView):
  model = Anime
  fields = ['title', 'creator', 'genre', 'release_year']

class AnimeUpdate(UpdateView):
  model = Anime
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['creator', 'genre', 'release_year']

class AnimeDelete(DeleteView):
  model = Anime
  success_url = '/anime'

class CharacterList(ListView):
  model = Character

class CharacterDetail(DetailView):
  model = Character

class CharacterCreate(CreateView):
  model = Character
  fields = '__all__'

class CharacterUpdate(UpdateView):
  model = Character
  fields = ['name', 'color']

class CharacterDelete(DeleteView):
  model = Character
  success_url = '/characters'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

 <h1>About the Anime Collector</h1>
 <hr>
 <p>Hire the Anime Collector!</p>
 <footer>All Rights Reserved, &copy; 2024 Anime Collector</footer>

 {% endblock %}

main_app/templates/anime/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Anime Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ anime.title}}</span>
        <p>Breed: {{ anime.creator }}</p>
        <p>Description: {{ anime.genre|linebreaks }}</p>
        <p>Anime Release Year: {{ anime.release_year}}</p>
      <div class="card-action">
        <a href="{% url 'anime_update' anime.id %}">Edit</a>
        <a href="{% url 'anime_delete' anime.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <form action="{% url 'add_episode' anime.id %}" method="POST">
      {% csrf_token %}
      {{ episode_form.as_p }}
      <input type="submit" class="btn" value="Add Episode">
    </form>
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Rating</th></tr>
      </thead>
      <tbody>
        {% for episode in anime.episode_set.all %}
          <tr>
            <td>{{episode.date}}</td>
            <td>{{episode.get_rating_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ anime.title }}'s Characters</h3>
    {% if anime.characters.count %}
      {% for character in anime.characters.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ character.name }}
            </span>
              </div>
              <div class="card-action">
                <form action="{% url 'remove_character' anime.id character.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="waves-effect waves-light btn-small">REMOVE
                    <i class="material-icons right">delete</i>
                  </button>
                </form>
              </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Characters 😿</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
<!-- New Markup Below -->
<div class="col s6">
<h3>Available Characters</h3>
{% if characters.count %}
  {% for character in characters.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A {{ character.name }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_character' anime.id character.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
  {% endfor %}
{% else %}
  <h5>{{anime.name}} Already Has All Characters Available</h5>
{% endif %}
</div>
<script>
  const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_rating');
  M.FormSelect.init(selectEl);

</script>



{% endblock %}

main_app/templates/anime/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Anime List</h1>

{% for anime in anime %}
  <div class="card">
    <a href="{% url 'detail' anime.id%}">
    <div class="card-content">
      <span class="card-title">{{ anime.title }}</span>
      <p>Creator: {{ anime.creator }}</p>
      <p>Genre: {{ anime.genre|linebreaks }}</p>
      <p>Anime Release Year: {{ anime.release_year}}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anime Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Anime Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'characters_create' %}">Add a Character</a></li>
          <li><a href="{% url 'characters_index' %}">View All Characters</a></li>
          <li><a href="{% url 'anime_create' %}">Add New Anime Series</a></li>
          <li><a href="{% url 'index' %}">View All My Anime</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2024 Anime Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

    <h1>Home</h1>


    {% endblock %} ```

main_app/templates/main_app/anime_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Anime</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' anime.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/anime_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.title}}</span></h1>
{% else %}
  <h1>Add Anime</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Character</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'characters_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/character_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Character Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ character.title }}</span>
        <!-- <p>Color: {{ toy.color }}</p> -->
      </div>
      <div class="card-action">
        <a href="{% url 'characters_update' toy.id %}">Edit</a>
        <a href="{% url 'characters_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/character_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.title}}</span></h1>
  {% else %}
    <h1>Add Character</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/character_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Character List</h1>

{% for character in character_list %}
  <a href="{% url 'characters_detail' character.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ character.name }}</span>
            <!-- <p>Color: {{ toy.color }}</p> -->
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}